noun = input("Enter random noun:")
verb = input("Enter random verb")
adjective = input("Enter random adjective")

print (f"I am a ninja I have fire power and {adjective} ")
print (f"I am a hot head and {noun} I did my daliy check up on the city")
print (f"I fought a powerful guy that was very strong and {verb}" )
print (f"I won the fight  and {noun} with some cut on my ninja suit") 
print ("but he was my friend and took home and we ate chipotle")

print (f"part 2 I after my friend woke up {noun} ate chipolte unilt we saw")
print (f"then me and my friend  look out side a we bad guy that were very power{adjective}")
print (f"they bet me and my friend in a fight but before that I save a girl name skylor {verb}")
print ("they challenge us in a 2k stage 3v3 party series we practice and won the party series and")
print ("bad ninjago got salty and we won the party and try to fight us and we won")